export const API = {
  AUTH: {
    LOGIN: "/auth/login",
    SIGNUP: "/auth/signup",
    PROFILE: "/auth/profile",
  },
  USER: {
    FETCH_ALL: "/users",
    FETCH_ONE: (id: string | number) => `/users/${id}`,
    FOLLOW: (id: string | number) => `/users/${id}/follow`,
    PROFILE: "/users/get-user-profile",
    GET_TOP_REVIEWERS: "users/get-top-reviewers/",
    UPLOAD_IMAGE: `/users/upload`,
    UPDATE_USER_PROFILE: `/users/update-user`,
  },
  GAME: {
    GET_TOP_RATED_GAMES: "game/get-top-rated-games",
    CREATE: "/game/create",
    LIST: "/game/list",
    GET_GAME: "/game/get-game",
    GET_GAMES: "/game/get-games",
  },
  REVIEWS: {
    CREATE_REVIEW: "review/create-review",
    GET_BY_GAMEID: "/review/get-by-gameid",
    GET_BY_USERID: "/review/get-by-user",
    RECENT_REVIEW: "/review/recent-review",
    TRENDING_REVIEW: "/review/trending-review",
    GET_REVIEW: "/review/get-review",
    UPDATE_REVIEW_VIEW: "/review/update-view",
    LIKE_REVIEW: "/review/like-review",
    SEARCH_REVIEW: "/review/search-review",
    DELETE_REVIEW: "/review/delete-review",
    UPDATE_REVIEW: "/review/update-review",
    ADD_COMMENT: "/review/add-comment",
    GET_COMMENTS: "/review/get-comments",
    UPDATE_COMMENT: "/review/update-comment",
    DELETE_COMMENT: "/review/delete-comment",
    GET_REVIEW_ANALYTICS: "/review/get-review-analytics",
    GET_ANALYTICS_OVERVIEW: "/review/get-analytics-overview",
    GET_FOLLOWING_REVIEWS: "/review/get-followers-review",
  },
  GENRE: {
    CREATE: "/genre/create",
    GET_ALL: "/genre",
  },
  DISCUSSIONS: {
    CREATE: "/discussion/create-discussion",
    GET_ALL: "/discussion/get-discussions",
    GET_ONE: (id: string) => `/discussion/get-discussion?${id}`,
  },
};
