export enum ServiceName {
  AUTH = 'AUTH_SERVICE',
  USER = 'USER_SERVICE',
  GAME = 'GAME_SERVICE',
  REVIEW = 'REVIEW_SERVICE',
}

export enum MessagePatterns {
  // Auth
  AUTH_SIGNUP = 'auth.signup',
  AUTH_SIGNIN = 'auth.signin',
  AUTH_VALIDATE = 'auth.validate',
  AUTH_REFRESH = 'auth.refresh',
  GOOGLE_AUTH = 'auth.google',
  // User
  USER_CREATE = 'user.create',
  USER_FIND_BY_ID = 'user.findById',
  USER_FIND_BY_EMAIL = 'user.findByEmail',
  UPDATE_USER = 'user.update',
  GET_USER = 'user.get.profile',
  USER_FOLLOW = 'user.follow',
  USER_UNFOLLOW = 'user.unfollow',
  GET_TOP_REVIEWERS = 'user.top.reviewers',
  USER_FIND_BY_GOOGLE_ID = 'user.findByGoogleId',
  // Game
  GAME_CREATE = 'game.create',
  GAME_UPDATE = 'game.update',
  GAME_DELETE = 'game.delete',
  GAME_GET = 'game.get',
  GET_GAMES = 'games.get',
  FIND_ONE_GAME = 'game.findone',
  GET_AI_OVERVIEW = 'game.ai.overview',
  GENERATE_AI_OVERVIEW = 'game.genereate.overview',

  CREATE_GENRE = 'game.genre',
  DELETE_GENRE = 'game.genre.delete',
  // Review
  CREATE_REVIEW = 'review.create',
  LIKE_REVIEW = 'review.like',
  GET_REVIEW = 'review.get',
  GET_TOP_RATED_GAME_IDS = 'review.top.rated.gameids',
  GET_TOP_RATED_GAMES = 'review.top.rated.games',
  INCREASE_VIEWS = 'review.views',
  TRENDING_REVIEWS = 'review.trending',
  RECENT_REVIEWS = 'review.recent',
  SEARCH_REVIEWS = 'review.search',
  GET_REVIEW_BY_GAMEID = 'review.gameId',
  GET_REVIEW_BY_USER = 'review.user',
  UPDATE_REVIEWS = 'review.update',
  DELETE_REVIEWS = 'review.delete',
  GET_OVERALL_RATING = 'review.rating',
  GET_REVIEW_ANALYTICS = 'review.analytics',
  GET_ANALYTICS_OVERVIEW = 'review.analytics.overview',
  GET_REVIEWS_BY_GAMEID = 'review.game.gameId',
  // Comment
  COMMENT_REVIEWS = 'review.comment',
  GET_COMMENT = 'comment.get',
  UPDATE_COMMENT = 'comment.update',
  DELETE_COMMENT = 'comment.delete',
}
